### ISSUE TITLE
W2S: no 300 tag crashes the process

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/overload#27]
If no 300 tag in retrieved from Worldcat record, W2S crashes.

**Comment by Mfgloger** [comment]
Traceback:
overload-2019-11-04 17:54:00,750-gui.py-490-ERROR-40-Unhandled error on W2S process. Traceback (most recent call last):\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/wc2sierra/gui.py', line 477, in launch_processing\n    id_type=self.id_type.get(), api=self.api.get())\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/wc2sierra/manager.py', line 510, in launch_process\n    xml_record, system, library, recap_no=recap_no)\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/wc2sierra/manager.py', line 128, in create_local_fields\n    leader_string, tag_008, tag_300a, cuttering_opts, order_data)\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/bibs/bpl_callnum.py', line 47, in create_bpl_fiction_callnum\n    if is_picture_book(audn_code, tag_300a):\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/bibs/parsers.py', line 83, in is_picture_book\n    if is_short(tag_300a):\n  File 'C:/Users/miriamgloger/Documents/GitHub/Overload/overload/bibs/parsers.py', line 54, in is_short\n    if 'volume' in tag_300a or ' v.' in tag_300a:\nTypeError: argument of type 'NoneType' is not iterable\n

(record  9788310132543 no 300)
--

**Comment by klinga** [comment]
fixed
