### ISSUE TITLE
BILINGUAL call numbers NYPL obsolete

### ISSUE THREAD

**Issue by Mfgloger** [BookOps-CAT/overload#61]
nypl_calnum.py          
if order_data
lines 86-99
                elif order_data.callLabel == "bil":
                    subfields.extend(["f", "BILINGUAL"])

NYPL does not use BILINGUAL as a classmark

**Comment by klinga** [comment]
done: https://github.com/BookOps-CAT/overload/commit/2afcbfc2a4fd725b6bceb24909209a98900f65f7
